queue_rules:
- name: default
  conditions:
  - label!=no-mergify
  - label!=WIP
  - -draft
  - approved-reviews-by=@fedora-infra/data-team
  - "#changes-requested-reviews-by=0"
  - status-success=Checks
  - status-success=Documentation
  - status-success=Unit tests (py36)
  - status-success=Unit tests (py37)
  - status-success=Unit tests (py38)
  - status-success=Unit tests (py39)



pull_request_rules:

- name: Automatic merge on approval
  actions:
    queue:
      method: rebase
      name: default
  conditions:
  - label!=no-mergify
  - label!=WIP
  - -draft
  - approved-reviews-by=@fedora-infra/data-team
  - "#changes-requested-reviews-by=0"
  - status-success=DCO
  - status-success=Checks
  - status-success=Documentation
  - status-success=Unit tests (py36)
  - status-success=Unit tests (py37)
  - status-success=Unit tests (py38)
  - status-success=Unit tests (py39)
