---
- name: Install RabbitMQ packages
  package:
      name: rabbitmq-server
      state: present

- name: Create RabbitMQ systemd override directory
  file:
    path: /etc/systemd/system/rabbitmq-server.service.d/
    state: directory

- name: Override rabbitmq hostname
  copy:
    content: "HOSTNAME=localhost"
    dest: /etc/rabbitmq/rabbitmq-env.conf
    mode: 0644

- name: Override file limit on rabbitmq
  copy:
    content: "[Service]\nLimitNOFILE=500000\n"
    dest: /etc/systemd/system/rabbitmq-server.service.d/override.conf

- name: start rabbitmq
  service: name=rabbitmq-server state=started enabled=yes
