on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

name: Run tests

jobs:

  checks:
    name: Checks
    runs-on: ubuntu-latest
    container: fedorapython/fedora-python-tox:latest
    steps:
      - uses: actions/checkout@v4

      - name: Mark the directory as safe for git
        run: git config --global --add safe.directory $PWD

      - name: Install RPM dependencies
        run: |
          dnf install -y krb5-devel pre-commit

      - name: Run pre-commit checks
        run: pre-commit run --all-files

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    container: fedorapython/fedora-python-tox:latest
    steps:
      - uses: actions/checkout@v4

      - name: Install RPM dependencies
        run: |
          dnf install -y krb5-devel
          pip install "poetry>=1.2"

      - name: Build the docs
        run: tox -e docs

      # - name: Save the docs
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: docs
      #     path: discourse2fedmsg/docs/_build/html


  unit_tests:
    name: Unit tests
    runs-on: ubuntu-latest
    container: fedorapython/fedora-python-tox:latest
    steps:
      - uses: actions/checkout@v4

      - name: Install RPM dependencies
        run: |
          dnf install -y krb5-devel libpq-devel
          pip install "poetry>=1.2"

      - name: Run unit tests with Tox
        run: tox -e ${{ matrix.tox_env }}-unittest

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v1
      #   with:
      #     name: ${{ matrix.tox_env }}
      #     flags: unittests
      #     env_vars: PYTHON
      #     fail_ci_if_error: true

    strategy:
      matrix:
        tox_env:
          - py37
          - py38
          - py39
          - py310
          - py311
